const express = require("express");
const router = express.Router();
const {adminJWTValidator} = require("../middleware/adminJWTValidator");
const deptController = require("../controller/deptController");
const { bodyValidator } = require("../middleware/bodyValidator");
router.post('/dept', bodyValidator(["name", "supervisor","employees"]),adminJWTValidator , deptController.create);
router.get('/dept',adminJWTValidator,deptController.read);
router.put('/dept/:id',adminJWTValidator, deptController.update );
router.delete('/dept/:id', adminJWTValidator, deptController.delete);
module.exports = router;